#!/bin/sh

# gather-libs v7.2
# Bruno "GNUser" Dantas GPLv3

# user variable:
template_dir=/opt/scripts/pack_template

main()
{
	sanity_checks "$@"
	cp -r $template_dir ./$1
	populate_libs_all "$@"
	copy_binary "$@"
	grab_manpage "$@"
	closing_remarks "$@"
}

sanity_checks()
{
	[ $# -ne 1 ] && echo "Exactly one argument (binary name) is required. Try again." && exit 1
	which "$1" >/dev/null || { echo "$1 not found in PATH. Try a different name."; exit 1; }
	echo "$1" | grep -q '/' && { echo "Not a path--just the name of the binary, please."; exit 1; }
}

populate_libs_all()
{
	fullpath="$(which "$1")"
	output_dir="./$1/libs-all"; [ ! -d $output_dir ] && mkdir -p $output_dir

	for lib in $(ldd "$fullpath" | fgrep '=>' | awk '{print $3}'); do
	    if [ -L "$lib" ]; then      # if lib is a link, copy link target then copy the link itself
	        link="$lib"
	        link_target="$(readlink -f "$link")"
	        cp "$link_target" "$output_dir"
	        cp -P "$link" "$output_dir" # -P means to copy links as a links, without following them to targets
	    else                        # if lib isn't a link, just copy it
	        cp "$lib" "$output_dir"
	    fi
	done
}

copy_binary()
{
	cp "$fullpath" ./$1/$1
	sed -i "s/XXXXX/$1/" ./$1/wrapper # replace the placeholder in wrapper script
}

grab_manpage()
{
	man "$1" >/dev/null 2>&1 && man "$1" 2>/dev/null | col -bx >./$1/${1}-manpage.txt 2>/dev/null
}

closing_remarks()
{
	echo "Success! See $(pwd)/$1"
	echo "Copy the above directory to target system then, in target system, run:
    ./filter-libs then 
    ./pack"
}

main "$@"
