#!/bin/sh

# unpack v9.0
# Bruno "GNUser" Dantas GPLv3

# user variable:
unpack_method=standard # either "standard" or "turbo"
# "standard" deletes TMPDIR after running (pro: we leave no trace; con: we need to recreate TMPDIR every run)
# "turbo" doesn't delete TMPDIR (pro: only first run creates TMPDIR, so subsequent runs are faster; con: less OCD)

ARCHIVE_STARTLINE=$(awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' "$0") # gets line number below "__ARCHIVE_BELOW__"

if [ "$1" = "unpack" ]; then
	runfiledir="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )" # ex: /home/bruno/Desktop
	if echo "$(basename "$0")" | grep -q '\.run$'; then 
		unpackfolder="$(basename "$0" .run)" # ex: runfile helloworld.run => unpackfolder helloworld
	else
		unpackfolder="$(basename "$0")_" # ex: runfile helloworld => unpackfolder helloworld_
	fi
	DEST_DIR="$runfiledir/$unpackfolder"; [ -d "$DEST_DIR" ] && rm -r "$DEST_DIR"; mkdir "$DEST_DIR"
	tail -n +$ARCHIVE_STARTLINE "$0" | tar xvzf - -C "$DEST_DIR"
	exit 0
else
	NAME="$(basename "$0")"
	if [ "$unpack_method" = "standard" ]; then
		export TMPDIR="$(mktemp -d "/tmp/$NAME-selfextract.XXXXXX")"
		tail -n +$ARCHIVE_STARTLINE "$0" | tar xvzf - -C "$TMPDIR" 1>/dev/null
		cleanup() { rm -rf "$TMPDIR"; }
		trap cleanup TERM INT HUP # just in case we never reach the 'cleanup' call below 
		"$TMPDIR/wrapper" "$@" # <-- POST-UNPACK COMMAND
		exit_status=$?
		cleanup
		exit $exit_status
	elif [ "$unpack_method" = "turbo" ]; then
		export TMPDIR="/tmp/$NAME-selfextract"
		if [ ! -d "$TMPDIR" ]; then
			mkdir "$TMPDIR"
			tail -n +$ARCHIVE_STARTLINE "$0" | tar xvzf - -C "$TMPDIR" 1>/dev/null
		fi
		exec "$TMPDIR/wrapper" "$@" # <-- POST-UNPACK COMMAND
	fi
fi

__ARCHIVE_BELOW__
