#!/bin/sh

# wrapper v8.0
# Bruno "GNUser" Dantas GPLv3

HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="$HERE/libs" 
export PATH="$HERE:$HERE/bins:$PATH"

# convert file and dir arguments to absolute paths before cd'ing
NEWARGS=""
for arg in "$@"; do
	if ([ -f "$arg" ] || [ -d "$arg" ]); then
		newarg="$(readlink -f "$arg")"
		NEWARGS="$NEWARGS \"$newarg\"" 
	else
		NEWARGS="$NEWARGS $arg" 
	fi
done

cd "$HERE"
eval exec XXXXX $NEWARGS
