#!/bin/sh

# wrapper v7.0
# Bruno "GNUser" Dantas GPLv3

HERE=$(dirname $(readlink -f "${0}"))
NAME=$(basename $(readlink -f "${0}"))

export LD_LIBRARY_PATH="$HERE/libs" 
#export PATH=$HERE/bins:$PATH

$HERE/XXXXX "$@"
