#!/bin/sh

# wrapper v8.0
# Bruno "GNUser" Dantas GPLv3

HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="$HERE/libs" 
export PATH="$HERE:$HERE/bins:$PATH"

# convert file/dir arguments to absolute paths before cd'ing
for arg in "$@"; do
	newarg="$(readlink -f "$arg" 2>/dev/null)"
	[ $? -eq 0 ] && NEWARGS="$NEWARGS \"$newarg\"" || NEWARGS="$NEWARGS $arg" 
done

cd "$HERE"
eval exec XXXXX $NEWARGS
